# Generated by Django 5.1.1 on 2024-09-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_doctorprofile_age_doctorprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
